1. Given a number, find the sum of its digits. Take the number as an input from the user.

In [1]:
num = input("Enter the number: ")
summ = 0
for i in num:
    summ = summ + int(i)
print(summ)

0

2. Given a number, check whether the given number is an Armstrong number or not. A positive integer is called an Armstrong number of order n if:
abcd... = an + bn + cn + dn + ...
Example: 153 = 1 * 1 * 1 + 5 * 5 * 5 + 3 * 3 * 3
153 is an Armstrong number of order 3.
Inputs from the user will be number and order n.

In [4]:
num = input("Enter the number: ")
n = int(input("Enter the order: "))
check = 0
print("The number entered is: ", num)
print("The order entered is: ", n)
for i in num:
    check = check + int(i) ** n
if check == int(num):
    print("Armstrong number")
else:
    print("Not an Armstrong number")

The number entered is:  153
The order entered is:  3
Armstrong number

In [ ]:
num = input("Enter the number: ")
n = int(input("Enter the order: "))
check = 0
print("The number entered is: ", num)
print("The order entered is: ", n)
for i in num:
    check = check + int(i) ** n
if check == int(num):
    print("Armstrong number")
else:
    print("Not an Armstrong number")

The number entered is:  152
The order entered is:  3
Not an Armstrong number

3. Given a string, write a python function to check if it is  palindrome or not. A string is said to be palindrome if the reverse of the string is the same as string. For example, “malayalam” is a palindrome, but “music” is not a palindrome.

In [ ]:
def palin(str):
    if str == str[::-1]:
        print("Palindrome")
    else:
        print("Not a Palindrome")


palin("malayalam")

Palindrome

In [ ]:
palin("music")

Not a Palindrome

4. Given an array which may contain duplicates, print all elements and their frequencies.

In [ ]:
arr = [1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
lmnts = []
cnt = []
for i in range(len(arr)):
    if arr[i] not in lmnts:
        lmnts.append(arr[i])
        cnt.append(1)
    else:
        idx = lmnts.index(arr[i])
        cnt[idx] += 1
print("Elements: ", lmnts)
print("Count: ", cnt)

Elements:  [1, 2, 3, 4, 5]
Count:  [2, 2, 2, 2, 2]

5. Given a number n, write a function to print all prime factors of n. For example, if the input number is 12, then output should be “2 2 3”.

In [ ]:
def prime_fac(n):
    chk = n
    prime = []
    while chk > 1:
        for i in range(2, n):
            if chk % i == 0:
                prime.append(i)
                chk = chk / i
                break
            else:
                continue
    print("Prime factors of ", n, " are: ", prime)


prime_fac(12)

Prime factors of  12  are:  [2, 2, 3]

In [ ]:
prime_fac(24)

Prime factors of  24  are:  [2, 2, 2, 3]

6. Given two numbers n and r, find the value of nCr (binomial coefficient: nCr = (n!) / (r! * (n-r)!))

In [ ]:
def bi_coef(n, r):
    if r < n:
        num = 1
        den1 = 1
        den2 = 1
        for i in range(n):
            num = num * (n - i)
        for i in range(r):
            den1 = den1 * (r - i)
        for i in range(n - r):
            den2 = den2 * (n - r - i)
        print("Numerator is: ", num)
        print("Denominator 1 is: ", den1)
        print("Denominator 2 is: ", den2)
        print("The binomial coefficient is: ", num / (den1 * den2))
    else:
        print("Not possible")


bi_coef(5, 2)

Numerator is:  120
Denominator 1 is:  2
Denominator 2 is:  6
The binomial coefficient is:  10.0

7. Searching: Given a sorted array arr[] of n elements, write a function to search a given element x in arr[]. Do it using linear and binary search techniques.

In [ ]:
# Gives the target elements' all actual index positions in any unsorted list using linear search algorithm as its base concept
def linear_search(lst, target):
    arr = []
    for i in range(len(lst)):
        if lst[i] == target:
            arr.append(i)
    if len(arr) > 0:
        print("Element found at index(s): ", arr)
    else:
        print("Element not found in the list.")


numbers = [10, 50, 30, 30, 70, 80, 20]
target_value = 30

linear_search(numbers, target_value)

Element found at index(s):  [2, 3]

In [ ]:
# Gives the target elements' all actual index positions in any unsorted list using binary search algorithm as its base concept
def binary_search(lst, target):
    low = 0
    high = len(lst) - 1
    left = -1
    lst = sorted([(v, i) for i, v in enumerate(lst)])
    # print("list: ", lst)
    while low <= high:
        mid = (low + high) // 2
        if lst[mid][0] == target:
            # print(mid)
            # return mid
            left = mid
            low = low
            high = mid - 1
        elif lst[mid][0] < target:
            low = mid + 1
            high = high
            # print(low, high)
        else:
            low = low
            high = mid - 1
            # print(low, high)
    if left == -1:
        return "Not Found"
    else:
        low = left
        high = len(lst) - 1
        right = -1
        while low <= high:
            mid = (low + high) // 2
            if lst[mid][0] == target:
                # print(mid)
                # return mid
                right = mid
                low = mid + 1
                high = high
            else:
                low = low
                high = mid - 1
    print(
        "Elements found at index(s): ", [lst[i][1] for i in range(left, right + 1)]
    )  # print(low, high)


numbers = [20, 10, 40, 50, 30, 30, 60, 10]
target_value = 30

binary_search(numbers, target_value)

Elements found at index(s):  [4, 5]

8. Input a text file (containing 1 or more paragraphs of English text) from the user, parse this file to display the frequency of occurrence of each word in this text file. Find the 3 most frequent words as well.

In [ ]:
file = open("question8_input.txt")
print(file)

<_io.TextIOWrapper name='question8_input.txt' mode='r' encoding='cp1252'>

In [ ]:
file_content = file.read()
file_content

'This is a sample text file for question 8.\nThis file contains several words and repeated words. This sample text is used to demonstrate word frequency counting.\n\nThis file contains several words and repeated words. This sample text is used to demonstrate word frequency counting.\nThe words in this file will be counted and the most frequent words will be displayed. This file contains repeated words to test the program.\n'

In [ ]:
lines = file_content.split("\n")
lines

['This is a sample text file for question 8.',
 'This file contains several words and repeated words. This sample text is used to demonstrate word frequency counting.',
 '',
 'This file contains several words and repeated words. This sample text is used to demonstrate word frequency counting.',
 'The words in this file will be counted and the most frequent words will be displayed. This file contains repeated words to test the program.',
 '']

In [ ]:
lines = [
    line.strip(".\n").strip("\n")
    for line in open("question8_input.txt")
    if line != "\n"
]
lines

['This is a sample text file for question 8',
 'This file contains several words and repeated words. This sample text is used to demonstrate word frequency counting',
 'This file contains several words and repeated words. This sample text is used to demonstrate word frequency counting',
 'The words in this file will be counted and the most frequent words will be displayed. This file contains repeated words to test the program']

In [ ]:
words = []
for line in lines:
    words.extend(line.strip(".").split(" "))
words

['This',
 'is',
 'a',
 'sample',
 'text',
 'file',
 'for',
 'question',
 '8',
 'This',
 'file',
 'contains',
 'several',
 'words',
 'and',
 'repeated',
 'words.',
 'This',
 'sample',
 'text',
 'is',
 'used',
 'to',
 'demonstrate',
 'word',
 'frequency',
 'counting',
 'This',
 'file',
 'contains',
 'several',
 'words',
 'and',
 'repeated',
 'words.',
 'This',
 'sample',
 'text',
 'is',
 'used',
 'to',
 'demonstrate',
 'word',
 'frequency',
 'counting',
 'The',
 'words',
 'in',
 'this',
 'file',
 'will',
 'be',
 'counted',
 'and',
 'the',
 'most',
 'frequent',
 'words',
 'will',
 'be',
 'displayed.',
 'This',
 'file',
 'contains',
 'repeated',
 'words',
 'to',
 'test',
 'the',
 'program']

In [ ]:
words_uniq = []
count = []
for i in range(len(words)):
    if words[i].lower() not in words_uniq:
        words_uniq.append(words[i].lower())
        count.append(1)
    else:
        j = words_uniq.index(words[i].lower())
        count[j] = count[j] + 1
print(words_uniq)
print(count)

['this', 'is', 'a', 'sample', 'text', 'file', 'for', 'question', '8', 'contains', 'several', 'words', 'and', 'repeated', 'words.', 'used', 'to', 'demonstrate', 'word', 'frequency', 'counting', 'the', 'in', 'will', 'be', 'counted', 'most', 'frequent', 'displayed.', 'test', 'program']
[7, 3, 1, 3, 3, 5, 1, 1, 1, 3, 2, 5, 3, 3, 2, 2, 3, 2, 2, 2, 2, 3, 1, 2, 2, 1, 1, 1, 1, 1, 1]

In [ ]:
len(words_uniq)

31

In [ ]:
len(count)

31

In [ ]:
final = []
for i in range(len(words_uniq)):
    final.append([count[i], words_uniq[i]])
final_sort = sorted(final, reverse=True)
final_sort

[[7, 'this'],
 [5, 'words'],
 [5, 'file'],
 [3, 'to'],
 [3, 'the'],
 [3, 'text'],
 [3, 'sample'],
 [3, 'repeated'],
 [3, 'is'],
 [3, 'contains'],
 [3, 'and'],
 [2, 'words.'],
 [2, 'word'],
 [2, 'will'],
 [2, 'used'],
 [2, 'several'],
 [2, 'frequency'],
 [2, 'demonstrate'],
 [2, 'counting'],
 [2, 'be'],
 [1, 'test'],
 [1, 'question'],
 [1, 'program'],
 [1, 'most'],
 [1, 'in'],
 [1, 'frequent'],
 [1, 'for'],
 [1, 'displayed.'],
 [1, 'counted'],
 [1, 'a'],
 [1, '8']]

9. A hospital is planning to digitize its patient record system to improve efficiency in managing patient information and billing. As a Python developer, you are tasked with building a simple system to process and analyze patient data. You are given a collection of patient details, where each record contains the patient’s name, age, disease, and total bill amount.
•	Store and organize patient data using appropriate data structures 
•	Calculate the number of patients affected by each disease 
•	Identify the patient with the highest bill amount 
•	Compute the average bill and display patients whose bill exceeds the average 
•	Ensure that duplicate patient entries are removed using suitable techniques

In [1]:
import pandas as pd

patients = [
    {"name": "Asha", "age": 45, "disease": "Fever", "bill": 1200},
    {"name": "Ravi", "age": 33, "disease": "Flu", "bill": 1800},
    {"name": "Meera", "age": 28, "disease": "Diabetes", "bill": 2500},
    {"name": "Asha", "age": 45, "disease": "Fever", "bill": 1200},
    {"name": "Karan", "age": 50, "disease": "Flu", "bill": 1400},
    {"name": "Neha", "age": 36, "disease": "Asthma", "bill": 2100},
]

patient_df = pd.DataFrame(patients)
patient_df

    name  age   disease  bill
0   Asha   45     Fever  1200
1   Ravi   33       Flu  1800
2  Meera   28  Diabetes  2500
3   Asha   45     Fever  1200
4  Karan   50       Flu  1400
5   Neha   36    Asthma  2100

In [2]:
patient_df = patient_df.drop_duplicates().reset_index(drop=True)
patient_df

    name  age   disease  bill
0   Asha   45     Fever  1200
1   Ravi   33       Flu  1800
2  Meera   28  Diabetes  2500
3  Karan   50       Flu  1400
4   Neha   36    Asthma  2100

In [3]:
# Count patients affected by each disease
disease_count = patient_df["disease"].value_counts()
disease_count

disease
Flu         2
Fever       1
Diabetes    1
Asthma      1
Name: count, dtype: int64

In [4]:
patient_df["bill"].idxmax()

2

In [5]:
# Find the patient with the highest bill
highest_bill_patient = patient_df.loc[patient_df["bill"].idxmax()]
highest_bill_patient

name          Meera
age              28
disease    Diabetes
bill           2500
Name: 2, dtype: object

In [6]:
# Compute average bill and list patients above average
average_bill = patient_df["bill"].mean()
average_bill

np.float64(1800.0)

In [7]:
above_average = patient_df[patient_df["bill"] > average_bill]
above_average

    name  age   disease  bill
2  Meera   28  Diabetes  2500
4   Neha   36    Asthma  2100

In [8]:
print("Unique patients:\n", patient_df)
print("\nDisease count:\n", disease_count)
print("\nPatient with highest bill:\n", highest_bill_patient)
print("\nAverage bill:", average_bill)
print("\nPatients above average:\n", above_average)

Unique patients:
     name  age   disease  bill
0   Asha   45     Fever  1200
1   Ravi   33       Flu  1800
2  Meera   28  Diabetes  2500
3  Karan   50       Flu  1400
4   Neha   36    Asthma  2100

Disease count:
 disease
Flu         2
Fever       1
Diabetes    1
Asthma      1
Name: count, dtype: int64

Patient with highest bill:
 name          Meera
age              28
disease    Diabetes
bill           2500
Name: 2, dtype: object

Average bill: 1800.0

Patients above average:
     name  age   disease  bill
2  Meera   28  Diabetes  2500
4   Neha   36    Asthma  2100

2. Online Food Delivery Analysis System
An online food delivery platform wants to analyze customer orders to understand business performance and customer preferences. Each order includes item names, quantities, and the restaurant from which the order was placed. As a developer, your task is to build a program that processes this data and generates meaningful insights.
•	Store order details in a structured format 
•	Calculate total revenue generated by each restaurant 
•	Identify the most frequently ordered item 
•	Detect and remove duplicate orders, if present 
•	Display the top-performing restaurant based on revenue

In [10]:
import pandas as pd

orders = [
    {"item": "Pizza", "quantity": 2, "restaurant": "Domino's"},
    {"item": "Burger", "quantity": 1, "restaurant": "Burger King"},
    {"item": "Pizza", "quantity": 2, "restaurant": "Domino's"},
    {"item": "Fries", "quantity": 3, "restaurant": "Burger King"},
    {"item": "Pasta", "quantity": 1, "restaurant": "Pizza Hut"},
    {"item": "Burger", "quantity": 1, "restaurant": "Burger King"},
]

order_df = pd.DataFrame(orders)
order_df

     item  quantity   restaurant
0   Pizza         2     Domino's
1  Burger         1  Burger King
2   Pizza         2     Domino's
3   Fries         3  Burger King
4   Pasta         1    Pizza Hut
5  Burger         1  Burger King

In [11]:
order_df = order_df.drop_duplicates().reset_index(drop=True)
order_df

     item  quantity   restaurant
0   Pizza         2     Domino's
1  Burger         1  Burger King
2   Fries         3  Burger King
3   Pasta         1    Pizza Hut

In [12]:
# Calculate revenue by restaurant
prices = {"Pizza": 250, "Burger": 180, "Fries": 80, "Pasta": 200}
order_df["revenue"] = order_df["item"].map(prices) * order_df["quantity"]
order_df

     item  quantity   restaurant  revenue
0   Pizza         2     Domino's      500
1  Burger         1  Burger King      180
2   Fries         3  Burger King      240
3   Pasta         1    Pizza Hut      200

In [13]:
restaurant_revenue = order_df.groupby("restaurant")["revenue"].sum()
restaurant_revenue

restaurant
Burger King    420
Domino's       500
Pizza Hut      200
Name: revenue, dtype: int64

In [14]:
# Most frequently ordered item
item_count = order_df["item"].value_counts()
item_count

item
Pizza     1
Burger    1
Fries     1
Pasta     1
Name: count, dtype: int64

In [15]:
item_count.idxmax()

'Pizza'

In [18]:
item_count.max()

np.int64(1)

In [19]:
most_frequent_item = item_count.idxmax(), item_count.max()
most_frequent_item

('Pizza', np.int64(1))

In [20]:
# Top-performing restaurant
top_restaurant = restaurant_revenue.idxmax(), restaurant_revenue.max()
top_restaurant

("Domino's", np.int64(500))

In [21]:
print("Unique orders:\n", order_df)
print("\nRevenue by restaurant:\n", restaurant_revenue)
print("\nMost frequently ordered item:", most_frequent_item)
print("\nTop-performing restaurant:", top_restaurant)

Unique orders:
      item  quantity   restaurant  revenue
0   Pizza         2     Domino's      500
1  Burger         1  Burger King      180
2   Fries         3  Burger King      240
3   Pasta         1    Pizza Hut      200

Revenue by restaurant:
 restaurant
Burger King    420
Domino's       500
Pizza Hut      200
Name: revenue, dtype: int64

Most frequently ordered item: ('Pizza', np.int64(1))

Top-performing restaurant: ("Domino's", np.int64(500))